name: GitHub Actions Deploy Angular App

on:
  push:
    branches:
    - main

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install --legacy-peer-deps
      run: npm install @angular/cli

    - name: Build
      run: npm run build

    - name: Deploy
      if: success()
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SOURCE: "dist/"
        REMOTE_HOST: ${{ secrets.SSH_REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.SSH_REMOTE_USER }}
        TARGET: ${{ secrets.SSH_REMOTE_TARGET }}
        EXCLUDE: "/dist/, /node_modules/"
